"""Add full-text search support

Revision ID: 30dbce16d3ea
Revises: 4cd6c02cf1b1
Create Date: 2025-10-24 12:35:17.928025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30dbce16d3ea'
down_revision = '4cd6c02cf1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(content, '') || ' ' || coalesce(subject, '') || ' ' || coalesce(teacher, ''))", persisted=True), nullable=True))

    # ### end Alembic commands ###
    op.create_index('ix_notes_search_vector', 'notes', ['search_vector'],
                    postgresql_using='gin')

def downgrade():
    op.drop_index('ix_notes_search_vector', table_name='notes')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
